kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: sonar-storage
  labels: 
    app: sonar-storage
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  zone: eu-west-2a
allowVolumeExpansion: true
