kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sonar-postgres-data
  labels: 
    app: Sonar-Postgres-Data
  annotations:
    volume.beta.kubernetes.io/storage-class: "sonar-storage"
spec:
  accessModes: 
    - ReadWriteOnce
  resources:
    requests: 
      storage: 4Gi
