kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: nexus-storage-data
  labels:
    app: nexus-storage-data
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  zone: eu-west-2a
allowVolumeExpansion: true