kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: nexus
spec:
  replicas: 1
  template:
    metadata:
      name: nexus
      labels: 
        app: nexus
    spec:
      securityContext:
        #runAsUser: 2000
        fsGroup: 2000
      containers:
        - name: nexus
          image: sonatype/nexus3:3.8.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
              name: nexusport
          volumeMounts:
            - name: nexus-data
              mountPath: /nexus-data
      volumes:
        - name: nexus-data
          persistentVolumeClaim:
            claimName: nexus-storage
    
