kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nexus-storage
  labels:
    app: nexus-storage
  annotations:
    volume.beta.kubernetes.io/storage-class: "nexus-storage-data"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi